### ISSUE TITLE
Teams references don't seem to work properly.

### ISSUE THREAD

**Issue by egonelbre** [storj/gerrit-codeowners#7]
Using team notes doesn't seem to work properly.

Error from gerrit log:
```
[2022-11-10T09:22:46.504Z] [ReceiveCommits-1[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTa
sk@53623584[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@755bb9f6[Wrapped task = com.go
ogle.gerrit.server.logging.LoggingContextAwareRunnable@7be04675]]]-for-SSH gerrit receive-pack /storj/gateway-m
t (egonelbre)] INFO  com.mjpitz.gerrit.plugins.codeowners.ReviewAssigner : assigning reviewers to storj%2Fgatew
ay-mt~main~Iebdc560368f83e78908b6fb9571980b31f7f8ee2
[2022-11-10T09:22:46.651Z] [ReceiveCommits-1[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTa
sk@53623584[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@755bb9f6[Wrapped task = com.go
ogle.gerrit.server.logging.LoggingContextAwareRunnable@7be04675]]]-for-SSH gerrit receive-pack /storj/gateway-m
t (egonelbre)] ERROR com.mjpitz.gerrit.plugins.codeowners.ReviewAssigner : failed to update reviewers on storj%
2Fgateway-mt~main~Iebdc560368f83e78908b6fb9571980b31f7f8ee2
org.kohsuke.github.GHFileNotFoundException: https://api.github.com/orgs/storj/teams/edge-team {"message":"Not F
ound","documentation_url":"https://docs.github.com/rest/reference/teams#get-a-team-by-name"}
        at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:540)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:401)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
        at org.kohsuke.github.Requester.fetch(Requester.java:76)
        at org.kohsuke.github.GHOrganization.getTeamBySlug(GHOrganization.java:194)
        at com.mjpitz.gerrit.plugins.codeowners.ReviewAssigner.fromCodeOwners(ReviewAssigner.java:135)
        at com.mjpitz.gerrit.plugins.codeowners.ReviewAssigner.assign(ReviewAssigner.java:199)
        at com.mjpitz.gerrit.plugins.codeowners.ReviewAssigner.onRevisionCreated(ReviewAssigner.java:293)
        at com.google.gerrit.server.extensions.events.RevisionCreated.lambda$fire$0(RevisionCreated.java:85)
        at com.google.gerrit.server.plugincontext.PluginContext.runLogExceptions(PluginContext.java:214)
        at com.google.gerrit.server.plugincontext.PluginSetContext.lambda$runEach$1(PluginSetContext.java:148)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.google.gerrit.server.plugincontext.PluginSetContext.runEach(PluginSetContext.java:148)
        at com.google.gerrit.server.extensions.events.RevisionCreated.fire(RevisionCreated.java:85)
        at com.google.gerrit.server.change.ChangeInserter.postUpdate(ChangeInserter.java:539)
        at com.google.gerrit.server.update.BatchUpdate.executePostOps(BatchUpdate.java:723)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:174)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:434)
        at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:1075)
```

**Comment by egonelbre** [comment]
This seems to be an authentication issue.

**Comment by egonelbre** [comment]
So what I've gathered so far, to setup authentication, I'll need to:

1. Change the code to allow using application installation token, loaded from the gerrit config (instead of loading it from the environement)
2. Create a new github app for the organization
3. Create an application installation token
4. Configure our gerrit plugin to use that installation token

Reference: https://github-api.kohsuke.org/githubappflow.html

**Comment by egonelbre** [comment]
An alternate approach would be to recreate the teams on Gerrit and then have an annotation that matches Github team name. Then look up team members from the local setup rather than querying Github API.
